---
title: "Scientific Visualization Application"
output: html_notebook
---
Plotly API:
```{r}
Sys.setenv("plotly_username"="jaclytn")
Sys.setenv("plotly_api_key"="8hHIJ4mxDoIgh2OiEJrK")
```
 
Willow Creek Data Import:
```{r}
data=read.csv("AMF_USWCr_2002_L2_WG_V004.csv",skip = 18,na.strings = c(-9999,-6999))[-1,] #Willow Creek
night = data$PAR < 1 & data$UST > 0.4 
dn <- data[night,]
```

Plotly!:
```{r}
wc <- plot_ly(data=data,x=data$DOY,y=data$NEE)
wc <- wc %>% layout(
  title = "Willow Creek",
  xaxis = list(domain = c(0.1, 1)),
  yaxis = list(title = "y"),
  updatemenus = list(
    list(
      y = 0.8,
      buttons = list(
        list(method = "restyle",
             args = list("type", "scatter"),
             label = "Scatter"),
        list(method = "restyle",
             args = list("type", "histogram2d"),
             label = "2D Histogram"))),
    list(
      y = 0.7,
      buttons = list(
        list(method = "restyle",
             args = list("x", list(data$NEE)),
             label = "Soil Water Content"),
        list(method = "restyle",
             args = list("x", list(data$TA)),
             label = "Air Temperature")))
  ))
wc
```

Publish:
```{r}
plotly_POST(wc, filename = "WC Test")
```



